#!/bin/bash

# meant to be run with `bash -c "/path/to/wlaunch"` when running from e.g. a Windows shortcut

# explicitly needed when launching with bash -c from Windows
cd ~
source ~/.bashrc
~/.scripts/config_process.py wsl ~/.config/i3/config.in ~/.config/i3/config
~/.scripts/wsl/process_screen_geometry.py "$@" ~/.config/i3/config

xrdb -merge ~/.Xresources

exec i3

